spring.application.name=csce548
spring.datasource.url=jdbc:mysql://localhost:3306/speedrun_app
spring.datasource.username=speedrun_db
spring.datasource.password=notmyrootpassword321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver